server:
  port: "${PORT:8080}"
springdoc:
  version: "${VERSION:1.0.0}"
  swagger-ui:
    path: "/"
    tagsSorter: alpha
spring:
  reactor:
    debug-agent: enabled
  mvc:
    log-request-details: true
    async:
      request-timeout: -1
package-zipper:
  maven-url: "https://repo1.maven.org/maven2"
